using static RetryFramework.SDL2.SDL;
using RetryFramework.SDL2;

namespace RetryFramework.Input;

/// <summary>
/// 키보드 키코드
/// </summary>
public enum Keycode
{
    Unknown = 0,

    Return = '\r',
    Escape = 27,
    Backspace = '\b',
    Tab = '\t',
    Space = ' ',
    Exclaim = '!',
    Quotedbl = '"',
    Hash = '#',
    Percent = '%',
    Dollar = '$',
    Ampersand = '&',
    Quote = '\'',
    Leftparen = '(',
    Rightparen = ')',
    Asterisk = '*',
    Plus = '+',
    Comma = ',',
    Minus = '-',
    Period = '.',
    Slash = '/',
    _0 = '0',
    _1 = '1',
    _2 = '2',
    _3 = '3',
    _4 = '4',
    _5 = '5',
    _6 = '6',
    _7 = '7',
    _8 = '8',
    _9 = '9',
    Colon = ':',
    Semicolon = ';',
    Less = '<',
    Equals = '=',
    Greater = '>',
    Question = '?',
    At = '@',
    Leftbracket = '[',
    Backslash = '\\',
    Rightbracket = ']',
    Caret = '^',
    Underscore = '_',
    Backquote = '`',
    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',

    CapsLock = SDL.SDL_Keycode.SDLK_CAPSLOCK,

    F1 = SDL.SDL_Keycode.SDLK_F1,
    F2 = SDL.SDL_Keycode.SDLK_F2,
    F3 = SDL.SDL_Keycode.SDLK_F3,
    F4 = SDL.SDL_Keycode.SDLK_F4,
    F5 = SDL.SDL_Keycode.SDLK_F5,
    F6 = SDL.SDL_Keycode.SDLK_F6,
    F7 = SDL.SDL_Keycode.SDLK_F7,
    F8 = SDL.SDL_Keycode.SDLK_F8,
    F9 = SDL.SDL_Keycode.SDLK_F9,
    F10 = SDL.SDL_Keycode.SDLK_F10,
    F11 = SDL.SDL_Keycode.SDLK_F11,
    F12 = SDL.SDL_Keycode.SDLK_F12,

    PrintScreen = SDL.SDL_Keycode.SDLK_PRINTSCREEN,
    ScrollLock = SDL.SDL_Keycode.SDLK_SCROLLLOCK,
    Pause = SDL.SDL_Keycode.SDLK_PAUSE,
    Insert = SDL.SDL_Keycode.SDLK_INSERT,
    Home = SDL.SDL_Keycode.SDLK_HOME,
    PageUp = SDL.SDL_Keycode.SDLK_PAGEUP,
    Delete = 127,
    End = SDL.SDL_Keycode.SDLK_END,
    PageDown = SDL.SDL_Keycode.SDLK_PAGEDOWN,
    Right = SDL.SDL_Keycode.SDLK_RIGHT,
    Left = SDL.SDL_Keycode.SDLK_LEFT,
    Down = SDL.SDL_Keycode.SDLK_DOWN,
    Up = SDL.SDL_Keycode.SDLK_UP,

    NumLockClear = SDL.SDL_Keycode.SDLK_NUMLOCKCLEAR,
    NumDivide = (int)SDL_Scancode.SDL_SCANCODE_KP_DIVIDE |  SCANCODE_MASK,
    NumMultiply = (int)SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY |  SCANCODE_MASK,
    NumMinus = (int)SDL_Scancode.SDL_SCANCODE_KP_MINUS |  SCANCODE_MASK,
    KP_PLUS = SDL.SDL_Keycode.SDLK_KP_PLUS,
    NumEnter = SDL.SDL_Keycode.SDLK_KP_ENTER,
    Num1 = SDL.SDL_Keycode.SDLK_KP_1,
    Num2 = SDL.SDL_Keycode.SDLK_KP_2,
    Num3 = SDL.SDL_Keycode.SDLK_KP_3,
    Num4 = SDL.SDL_Keycode.SDLK_KP_4,
    Num5 = SDL.SDL_Keycode.SDLK_KP_5,
    Num6 = SDL.SDL_Keycode.SDLK_KP_6,
    Num7 = SDL.SDL_Keycode.SDLK_KP_7,
    Num8 = SDL.SDL_Keycode.SDLK_KP_8,
    Num9 = SDL.SDL_Keycode.SDLK_KP_9,
    Num0 = SDL.SDL_Keycode.SDLK_KP_0,
    NumPeriod = (int)SDL_Scancode.SDL_SCANCODE_KP_PERIOD | SCANCODE_MASK,

    Application = (int)SDL_Scancode.SDL_SCANCODE_APPLICATION | SCANCODE_MASK,
    Power = SDL.SDL_Keycode.SDLK_POWER,
    KP_EQUALS = (int)SDL_Scancode.SDL_SCANCODE_KP_EQUALS | SCANCODE_MASK,
    F13 = (int)SDL_Scancode.SDL_SCANCODE_F13 | SCANCODE_MASK,
    F14 = (int)SDL_Scancode.SDL_SCANCODE_F14 | SCANCODE_MASK,
    F15 = (int)SDL_Scancode.SDL_SCANCODE_F15 | SCANCODE_MASK,
    F16 = (int)SDL_Scancode.SDL_SCANCODE_F16 | SCANCODE_MASK,
    F17 = (int)SDL_Scancode.SDL_SCANCODE_F17 | SCANCODE_MASK,
    F18 = (int)SDL_Scancode.SDL_SCANCODE_F18 | SCANCODE_MASK,
    F19 = (int)SDL_Scancode.SDL_SCANCODE_F19 | SCANCODE_MASK,
    F20 = (int)SDL_Scancode.SDL_SCANCODE_F20 | SCANCODE_MASK,
    F21 = (int)SDL_Scancode.SDL_SCANCODE_F21 | SCANCODE_MASK,
    F22 = (int)SDL_Scancode.SDL_SCANCODE_F22 | SCANCODE_MASK,
    F23 = (int)SDL_Scancode.SDL_SCANCODE_F23 | SCANCODE_MASK,
    F24 = (int)SDL_Scancode.SDL_SCANCODE_F24 | SCANCODE_MASK,
    Execute = (int)SDL_Scancode.SDL_SCANCODE_EXECUTE | SCANCODE_MASK,
    Help = (int)SDL_Scancode.SDL_SCANCODE_HELP | SCANCODE_MASK,
    Menu = (int)SDL_Scancode.SDL_SCANCODE_MENU | SCANCODE_MASK,
    Select = (int)SDL_Scancode.SDL_SCANCODE_SELECT | SCANCODE_MASK,
    Stop = (int)SDL_Scancode.SDL_SCANCODE_STOP | SCANCODE_MASK,
    Again = (int)SDL_Scancode.SDL_SCANCODE_AGAIN | SCANCODE_MASK,
    Undo = (int)SDL_Scancode.SDL_SCANCODE_UNDO | SCANCODE_MASK,
    Cut = (int)SDL_Scancode.SDL_SCANCODE_CUT | SCANCODE_MASK,
    Copy = (int)SDL_Scancode.SDL_SCANCODE_COPY | SCANCODE_MASK,
    Paste = (int)SDL_Scancode.SDL_SCANCODE_PASTE | SCANCODE_MASK,
    Find = (int)SDL_Scancode.SDL_SCANCODE_FIND | SCANCODE_MASK,
    Mute = (int)SDL_Scancode.SDL_SCANCODE_MUTE | SCANCODE_MASK,
    VolumeUp = (int)SDL_Scancode.SDL_SCANCODE_VOLUMEUP | SCANCODE_MASK,
    VolumeDown = (int)SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN | SCANCODE_MASK,
    KP_Comma = (int)SDL_Scancode.SDL_SCANCODE_KP_COMMA | SCANCODE_MASK,
    KP_EQUALSAS400 = (int)SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400 | SCANCODE_MASK,

    // ALTERASE = (int)SDL_Scancode.SDL_SCANCODE_ALTERASE |  SCANCODE_MASK,
    // SYSREQ = (int)SDL_Scancode.SDL_SCANCODE_SYSREQ |  SCANCODE_MASK,
    // CANCEL = (int)SDL_Scancode.SDL_SCANCODE_CANCEL |  SCANCODE_MASK,
    // CLEAR = (int)SDL_Scancode.SDL_SCANCODE_CLEAR |  SCANCODE_MASK,
    // PRIOR = (int)SDL_Scancode.SDL_SCANCODE_PRIOR |  SCANCODE_MASK,
    // RETURN2 = (int)SDL_Scancode.SDL_SCANCODE_RETURN2 |  SCANCODE_MASK,
    // SEPARATOR = (int)SDL_Scancode.SDL_SCANCODE_SEPARATOR |  SCANCODE_MASK,
    // OUT = (int)SDL_Scancode.SDL_SCANCODE_OUT |  SCANCODE_MASK,
    // OPER = (int)SDL_Scancode.SDL_SCANCODE_OPER |  SCANCODE_MASK,
    // CLEARAGAIN = (int)SDL_Scancode.SDL_SCANCODE_CLEARAGAIN |  SCANCODE_MASK,
    // CRSEL = (int)SDL_Scancode.SDL_SCANCODE_CRSEL |  SCANCODE_MASK,
    // EXSEL = (int)SDL_Scancode.SDL_SCANCODE_EXSEL |  SCANCODE_MASK,

    // KP_00 = (int)SDL_Scancode.SDL_SCANCODE_KP_00 |  SCANCODE_MASK,
    // KP_000 = (int)SDL_Scancode.SDL_SCANCODE_KP_000 |  SCANCODE_MASK,
    // THOUSANDSSEPARATOR =
    //(int)SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR |  SCANCODE_MASK,
    // DECIMALSEPARATOR =
    //(int)SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR |  SCANCODE_MASK,
    // CURRENCYUNIT = (int)SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT |  SCANCODE_MASK,
    // CURRENCYSUBUNIT =
    //(int)SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT |  SCANCODE_MASK,
    // KP_LEFTPAREN = (int)SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN |  SCANCODE_MASK,
    // KP_RIGHTPAREN = (int)SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN |  SCANCODE_MASK,
    // KP_LEFTBRACE = (int)SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE |  SCANCODE_MASK,
    // KP_RIGHTBRACE = (int)SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE |  SCANCODE_MASK,
    // KP_TAB = (int)SDL_Scancode.SDL_SCANCODE_KP_TAB |  SCANCODE_MASK,
    // KP_BACKSPACE = (int)SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE |  SCANCODE_MASK,
    // KP_A = (int)SDL_Scancode.SDL_SCANCODE_KP_A |  SCANCODE_MASK,
    // KP_B = (int)SDL_Scancode.SDL_SCANCODE_KP_B |  SCANCODE_MASK,
    // KP_C = (int)SDL_Scancode.SDL_SCANCODE_KP_C |  SCANCODE_MASK,
    // KP_D = (int)SDL_Scancode.SDL_SCANCODE_KP_D |  SCANCODE_MASK,
    // KP_E = (int)SDL_Scancode.SDL_SCANCODE_KP_E |  SCANCODE_MASK,
    // KP_F = (int)SDL_Scancode.SDL_SCANCODE_KP_F |  SCANCODE_MASK,
    // KP_XOR = (int)SDL_Scancode.SDL_SCANCODE_KP_XOR |  SCANCODE_MASK,
    // KP_POWER = (int)SDL_Scancode.SDL_SCANCODE_KP_POWER |  SCANCODE_MASK,
    // KP_PERCENT = (int)SDL_Scancode.SDL_SCANCODE_KP_PERCENT |  SCANCODE_MASK,
    // KP_LESS = (int)SDL_Scancode.SDL_SCANCODE_KP_LESS |  SCANCODE_MASK,
    // KP_GREATER = (int)SDL_Scancode.SDL_SCANCODE_KP_GREATER |  SCANCODE_MASK,
    // KP_AMPERSAND = (int)SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND |  SCANCODE_MASK,
    // KP_DBLAMPERSAND =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND |  SCANCODE_MASK,
    // KP_VERTICALBAR =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR |  SCANCODE_MASK,
    // KP_DBLVERTICALBAR =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR |  SCANCODE_MASK,
    // KP_COLON = (int)SDL_Scancode.SDL_SCANCODE_KP_COLON |  SCANCODE_MASK,
    // KP_HASH = (int)SDL_Scancode.SDL_SCANCODE_KP_HASH |  SCANCODE_MASK,
    // KP_SPACE = (int)SDL_Scancode.SDL_SCANCODE_KP_SPACE |  SCANCODE_MASK,
    // KP_AT = (int)SDL_Scancode.SDL_SCANCODE_KP_AT |  SCANCODE_MASK,
    // KP_EXCLAM = (int)SDL_Scancode.SDL_SCANCODE_KP_EXCLAM |  SCANCODE_MASK,
    // KP_MEMSTORE = (int)SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE |  SCANCODE_MASK,
    // KP_MEMRECALL = (int)SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL |  SCANCODE_MASK,
    // KP_MEMCLEAR = (int)SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR |  SCANCODE_MASK,
    // KP_MEMADD = (int)SDL_Scancode.SDL_SCANCODE_KP_MEMADD |  SCANCODE_MASK,
    // KP_MEMSUBTRACT =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT |  SCANCODE_MASK,
    // KP_MEMMULTIPLY =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY |  SCANCODE_MASK,
    // KP_MEMDIVIDE = (int)SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE |  SCANCODE_MASK,
    // KP_PLUSMINUS = (int)SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS |  SCANCODE_MASK,
    // KP_CLEAR = (int)SDL_Scancode.SDL_SCANCODE_KP_CLEAR |  SCANCODE_MASK,
    // KP_CLEARENTRY = (int)SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY |  SCANCODE_MASK,
    // KP_BINARY = (int)SDL_Scancode.SDL_SCANCODE_KP_BINARY |  SCANCODE_MASK,
    // KP_OCTAL = (int)SDL_Scancode.SDL_SCANCODE_KP_OCTAL |  SCANCODE_MASK,
    // KP_DECIMAL = (int)SDL_Scancode.SDL_SCANCODE_KP_DECIMAL |  SCANCODE_MASK,
    // KP_HEXADECIMAL =
    //(int)SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL |  SCANCODE_MASK,

    LeftCTRL = SDL.SDL_Keycode.SDLK_LCTRL,
    LeftSHIFT = SDL.SDL_Keycode.SDLK_LSHIFT,
    LeftALT = SDL.SDL_Keycode.SDLK_LALT,
    LeftGUI = SDL.SDL_Keycode.SDLK_LGUI,
    RightCTRL = SDL.SDL_Keycode.SDLK_RCTRL,
    RightSHIFT = SDL.SDL_Keycode.SDLK_RSHIFT,
    RightALT = SDL.SDL_Keycode.SDLK_RALT,
    RightGUI = SDL.SDL_Keycode.SDLK_RGUI,

    Mode = (int)SDL_Scancode.SDL_SCANCODE_MODE |  SCANCODE_MASK,

    AudioNext = (int)SDL_Scancode.SDL_SCANCODE_AUDIONEXT |  SCANCODE_MASK,
    AudioPrev = (int)SDL_Scancode.SDL_SCANCODE_AUDIOPREV |  SCANCODE_MASK,
    AudioStop = (int)SDL_Scancode.SDL_SCANCODE_AUDIOSTOP |  SCANCODE_MASK,
    AudioPlay = (int)SDL_Scancode.SDL_SCANCODE_AUDIOPLAY |  SCANCODE_MASK,
    AudioMute = (int)SDL_Scancode.SDL_SCANCODE_AUDIOMUTE |  SCANCODE_MASK,
    MediaSelect = (int)SDL_Scancode.SDL_SCANCODE_MEDIASELECT | SCANCODE_MASK,
    WWW = (int)SDL_Scancode.SDL_SCANCODE_WWW | SCANCODE_MASK,
    Mail = (int)SDL_Scancode.SDL_SCANCODE_MAIL | SCANCODE_MASK,
    Calculator = (int)SDL_Scancode.SDL_SCANCODE_CALCULATOR |    SCANCODE_MASK,
    Computer = (int)SDL_Scancode.SDL_SCANCODE_COMPUTER | SCANCODE_MASK,
    ACSearch = (int)SDL_Scancode.SDL_SCANCODE_AC_SEARCH | SCANCODE_MASK,
    ACHome = (int)SDL_Scancode.SDL_SCANCODE_AC_HOME | SCANCODE_MASK,
    ACBack = (int)SDL_Scancode.SDL_SCANCODE_AC_BACK | SCANCODE_MASK,
    ACForward = (int)SDL_Scancode.SDL_SCANCODE_AC_FORWARD | SCANCODE_MASK,
    ACStop = (int)SDL_Scancode.SDL_SCANCODE_AC_STOP | SCANCODE_MASK,
    ACRefresh = (int)SDL_Scancode.SDL_SCANCODE_AC_REFRESH | SCANCODE_MASK,
    ACBookmarks = (int)SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS | SCANCODE_MASK,

    BrightnessDown = SDL.SDL_Keycode.SDLK_BRIGHTNESSDOWN,
    BrightnessUp = SDL.SDL_Keycode.SDLK_BRIGHTNESSUP,
    DisplaySwitch = (int)SDL_Scancode.SDL_SCANCODE_DISPLAYSWITCH | SCANCODE_MASK,
    //KBDILLUMTOGGLE = (int)SDL_Scancode.SDL_SCANCODE_KBDILLUMTOGGLE | SCANCODE_MASK,
    //KBDILLUMDOWN = (int)SDL_Scancode.SDL_SCANCODE_KBDILLUMDOWN | SCANCODE_MASK,
    //KBDILLUMUP = (int)SDL_Scancode.SDL_SCANCODE_KBDILLUMUP | SCANCODE_MASK,
    Eject = (int)SDL_Scancode.SDL_SCANCODE_EJECT | SCANCODE_MASK,
    Sleep = (int)SDL_Scancode.SDL_SCANCODE_SLEEP | SCANCODE_MASK,
    App1 = (int)SDL_Scancode.SDL_SCANCODE_APP1 | SCANCODE_MASK,
    App2 = (int)SDL_Scancode.SDL_SCANCODE_APP2 | SCANCODE_MASK,

    AudioRewind = (int)SDL_Scancode.SDL_SCANCODE_AUDIOREWIND | SCANCODE_MASK,
    AudioFastForward = (int)SDL_Scancode.SDL_SCANCODE_AUDIOFASTFORWARD | SCANCODE_MASK
}